services:
  ffc-ice-bank:
    build:
      context: .
      target: production
    image: ffc-ice-bank
    container_name: ffc-ice-bank
    environment:
      APPINSIGHTS_CLOUDROLE: ffc-ice-bank-local
      APPINSIGHTS_CONNECTIONSTRING: ${APPINSIGHTS_CONNECTIONSTRING}
