{{- include "ffc-helm-library.container-secret" (list . "ffc-ice-bank.container-secret") -}}
{{- define "ffc-ice-bank.container-secret" -}}
stringData:
  {{- if .Values.appInsights.connectionString }}
  APPINSIGHTS_CONNECTIONSTRING: {{ quote .Values.appInsights.connectionString }}
  {{- end }}
  {{- if .Values.container.serviceBusConnectionString }}
  SERVICE_BUS_CONNECTION_STRING: {{ quote .Values.container.serviceBusConnectionString }}
  {{- end }}
  {{- if .Values.container.serviceBusUsername }}
  SERVICE_BUS_USERNAME: {{ quote .Values.container.serviceBusUsername }}
  {{- end }}
  {{- if .Values.container.serviceBusPassword }}
  SERVICE_BUS_PASSWORD: {{ quote .Values.container.serviceBusPassword }}
  {{- end }}
  {{- if .Values.container.d365TenantID }}
  D365_TENANT_ID: {{ quote .Values.container.d365TenantID }}
  {{- end }}
  {{- if .Values.container.d365ClientID }}
  D365_CLIENT_ID: {{ quote .Values.container.d365ClientID }}
  {{- end }}
  {{- if .Values.container.d365ClientSecret }}
  D365_CLIENT_SECRET: {{ quote .Values.container.d365ClientSecret }}
  {{- end }}
{{- end -}}
